application: news-farmer
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /update
  script: update.app

- url: /categories.*
  script: categories.app

- url: /publishers.*
  script: publishers.app

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
